# Generated by Django 3.0.7 on 2020-06-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ins_Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.IntegerField()),
                ('Name', models.CharField(max_length=30)),
                ('Phy_Marks', models.IntegerField()),
                ('Chem_Marks', models.IntegerField()),
                ('Math_Marks', models.IntegerField()),
            ],
        ),
    ]
