# Generated by Django 3.0.7 on 2020-06-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ins_Marks',
            new_name='Ins_Mark',
        ),
    ]
