# Generated by Django 3.0.7 on 2020-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200613_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('j', 'Java'), ('p', 'Python'), ('c', 'C/C++')], max_length=1)),
                ('question', models.CharField(max_length=300)),
                ('ans', models.TextField()),
            ],
        ),
    ]
